#!/usr/bin/env python3
# =====================================================================
#  zs_m50_verify_v1_3.py
#  Verification suite for ZS-M50 v1.3
#  "The Horizontal Cyclotomic Dynamics of Polygon Tetration"
#  Kenny Kang | Z-Spin Collaboration | Mathematical Spine Theme
#
#  Zero free parameters. (A, Q, dim Z) = (35/437, 11, 2) LOCKED.
#
#  This suite is FAIL-CLOSED: it aborts with a non-zero exit code if
#  (a) any executable check returns False, or (b) the number of executed
#  checks differs from EXPECTED_CHECKS. Declarations of OPEN gates and
#  external imports are logged via register() and are NOT counted as
#  verification evidence.
#
#  SCOPE NOTES (mirrors the v1.3 body):
#   * The ALG-block CONSTRUCTS the Bost-Connes representation on l^2(N^x)
#     internally and verifies all covariance relations exactly -> closes
#     gate H-ALG (PROVEN).
#   * The NG-block proves no finite register carries a proper isometry
#     -> H-BC requires an infinite-dimensional completion.
#   * The G-block is a FORMAL-IDENTITY (Euler consistency), NOT an orbit
#     construction.
#   * The core theorem M50.3' is DERIVED-CONDITIONAL on the remaining
#     gates {H-FLOW, H-SB, H-WEIGHT, P-TRANS}; these are REGISTERED, not
#     claimed PASS.
#
#  Dependencies: numpy, mpmath
# =====================================================================

import sys, cmath, math
from fractions import Fraction as Fr
import numpy as np
import mpmath as mp

mp.mp.dps = 40
EXPECTED_CHECKS = 36

# --------------------------------------------------------------------
#  harness
# --------------------------------------------------------------------
_checks = []          # executable, counted, fail-closed
_regs = []            # declarations, not counted
def check(cid, desc, ok, status):
    _checks.append((bool(ok), cid, desc, status))
    print(f"[{'PASS' if ok else 'FAIL'}] {cid:<8} {desc}  [{status}]")
def register(cid, desc, status):
    _regs.append((cid, desc, status))
    print(f"[REG ] {cid:<8} {desc}  [{status}]")
def banner(t):
    print("\n" + "=" * 72 + f"\n{t}\n" + "=" * 72)

def sieve(N):
    b = [True] * N; b[0] = b[1] = False
    for i in range(2, int(N ** 0.5) + 1):
        if b[i]:
            for j in range(i * i, N, i): b[j] = False
    return [i for i in range(N) if b[i]]

Q = 11
PRIMES_SMALL = [2, 3, 5, 7, 11, 13]
def normalize(x): return Fr(x.numerator % x.denominator, x.denominator)

# =====================================================================
#  BLOCK T1 — lifted base-dilation identity  [PROVEN]
# =====================================================================
banner("BLOCK T1 : lifted base-dilation identity  F_a o D_m = F_{ma}")
def Fa(a, z): return mp.e ** (a * z)
a = mp.log(mp.e ** (2j * mp.pi / 5))
ok_id = ok_nc = True
for m in [2, 3, 5]:
    for z in [mp.mpf("0.3") + 0.2j, 1 + 0j, 0.5j]:
        if abs(Fa(a, m * z) - Fa(m * a, z)) > mp.mpf(10) ** (-30): ok_id = False
        if abs(m * Fa(a, z) - Fa(a, m * z)) < mp.mpf(10) ** (-6): ok_nc = False
check("T1.1", "F_a(D_m z) = F_{ma}(z)", ok_id, "PROVEN")
check("T1.2", "D_m F_a != F_a D_m (source-target, not a symmetry)", ok_nc, "PROVEN")

# =====================================================================
#  BLOCK T2 — cyclotomic SATURATION  Sat_{N^x}{1/n} = Q/Z  [PROVEN]
#  (terminology fixed: 'saturation', not topological 'closure' — mu_inf
#   is dense in S^1; the semigroup saturation is Q/Z.)
# =====================================================================
banner("BLOCK T2 : N^x-saturation of the polygon family = Q/Z")
ok_closed = True
for n in [3, 4, 5, 7]:
    x = Fr(1, n)
    for m in range(1, 13):
        if normalize(Fr(m) * x).denominator > n: ok_closed = False
check("T2.1", "N^x-orbit of 1/n stays in (1/n)Z/Z", ok_closed, "PROVEN")

# real action test (v1.1 tautology removed): orbit via ACTION vs target via ENUMERATION
ok_sat = True
for n in [3, 4, 5, 7, 9]:
    x = Fr(1, n)
    powers = {normalize(Fr(m) * x) for m in range(n)}          # generated by action m*x
    target = {normalize(Fr(k, n)) for k in range(n)}           # enumerated k/n
    if powers != target: ok_sat = False
check("T2.2", "Sat_{N^x}{1/n} = full n-torsion (action==enumeration, not tautology)",
      ok_sat, "PROVEN")

x_unit = mp.log(mp.e ** (2j * mp.pi / 4)) / (2j * mp.pi)
x_gen = mp.log(mp.mpf("1.7") * mp.e ** (2j * mp.pi / 4)) / (2j * mp.pi)
check("T2.3", "base coord: |b|=1 -> R/Z, |b|!=1 -> C/Z",
      abs(mp.im(x_unit)) < mp.mpf(10) ** (-30) and abs(mp.im(x_gen)) > 1e-6, "PROVEN")

# =====================================================================
#  BLOCK T3 — finite-level cyclotomic Frobenius (ZS-M22)  [PROVEN]
# =====================================================================
banner("BLOCK T3 : Frobenius gate M_p|a> = |pa mod 11> ; character diag")
units = list(range(1, Q)); g = 2; ind = {}; x = 1
for k in range(Q - 1): ind[x] = k; x = (x * g) % Q
def chi_k(kk, aa):
    aa %= Q
    return 0 if aa == 0 else np.exp(2j * np.pi * kk * ind[aa] / (Q - 1))
def Mp(p):
    M = np.zeros((Q - 1, Q - 1), complex)
    for i, aa in enumerate(units): M[units.index((p * aa) % Q), i] = 1
    return M
ok_eig = True
for p in [2, 3, 7, 13]:
    ev = sorted(np.linalg.eigvals(Mp(p)), key=lambda z: (round(z.real, 6), round(z.imag, 6)))
    cv = sorted([complex(chi_k(k, p)) for k in range(Q - 1)],
                key=lambda z: (round(z.real, 6), round(z.imag, 6)))
    if not np.allclose(ev, cv, atol=1e-9): ok_eig = False
check("T3.1", "eig(M_p) = {chi_k(p)}", ok_eig, "PROVEN")
p, s = 3, 2.0 + 0j
det = np.linalg.det(np.eye(Q - 1) - p ** (-s) * Mp(p))
euler = np.prod([1 - chi_k(k, p) * p ** (-s) for k in range(Q - 1)])
check("T3.2", "det(I - p^-s M_p) = prod_k (1 - chi_k(p) p^-s)", abs(det - euler) < 1e-9, "PROVEN")
n = p = 3
orbit = [(p * k) % n for k in range(n)]
check("C.1", "ramified p|n: zeta=1 FIXED, primitive stratum loses automorphy",
      orbit[0] == 0 and orbit[1] == 0 and orbit[2] == 0, "PROVEN")

# =====================================================================
#  BLOCK T4 — logarithmic time cocycle  [PROVEN]
# =====================================================================
banner("BLOCK T4 : log-time cocycle tau(m)=log m ; {log p} Q-independent")
ok_coc = all(abs(mp.log(m * mm) - (mp.log(m) + mp.log(mm))) < mp.mpf(10) ** (-30)
             for m in [2, 3, 6] for mm in [5, 7, 10])
check("T4.1", "tau(m m') = tau(m)+tau(m')", ok_coc, "PROVEN")
rel = mp.pslq([mp.log(2), mp.log(3), mp.log(5)], maxcoeff=10 ** 8, maxsteps=10 ** 4)
check("T4.2", "no integer relation among {log2,log3,log5} (PSLQ)", rel is None, "PROVEN")
# T4.3 UFD: prod p^a = 1 => a = 0 (unique factorisation is the PROOF; PSLQ is regression)
import itertools
ufd_ok = not any(
    any(cf) and abs(math.prod(pp ** a for pp, a in zip([2, 3, 5, 7], cf)) - 1.0) < 1e-12
    for cf in itertools.product(range(-3, 4), repeat=4))
check("T4.3", "prod p^a = 1 => all a=0 (UFD proof; PSLQ above is regression only)", ufd_ok, "PROVEN")

# =====================================================================
#  BLOCK C — four-point level correction  [PROVEN]
# =====================================================================
banner("BLOCK C : 'period-4' -> four-point level mu_4")
orbit14 = {normalize(Fr(m) * Fr(1, 4)) for m in range(0, 40)}
is_mu4 = orbit14 == {Fr(0, 1), Fr(1, 4), Fr(1, 2), Fr(3, 4)}
def traj(m, x0=Fr(1, 4), steps=6):
    seq = [x0]
    for _ in range(steps): seq.append(normalize(Fr(m) * seq[-1]))
    return seq
t2, t3, t5 = traj(2), traj(3), traj(5)
check("C.2", "orbit(1/4) SET = mu_4 (4 points)", is_mu4, "PROVEN")
check("C.3", "no single multiplier is a length-4 orbit (m=2 absorbed / m=3 2-cycle / m=5 fixed)",
      t2[-1] == Fr(0, 1) and (t3[0] == t3[2] and t3[0] != t3[1]) and t5[0] == t5[1], "PROVEN")

# =====================================================================
#  BLOCK HD — half-density localisation (Theorem M50.HD)
# =====================================================================
banner("BLOCK HD : fibre p^{+m/2} (kernel-derived) vs base p^{-m/2} (KMS)")
# HD.1: flat trace from the DISTRIBUTIONAL KERNEL, not from the closed form.
# K_m(x,y)=p^{-ms} sum_{j} delta(y-(x+j)/p^m); flat trace = sum over roots
# x*=j/(p^m-1) in [0,1) with Jacobian 1/|1-p^-m|.
def flat_trace_kernel(p, m, s):
    N = p ** m
    nroots = sum(1 for j in range(N) if 0 <= j / (N - 1) < 1)   # = p^m - 1
    return p ** (-m * s) * nroots / abs(1 - p ** (-m))
ok_hd1 = all(abs(flat_trace_kernel(p, m, 0.5) - p ** (m * 0.5)) < 1e-9
             for p in [2, 3, 5] for m in [1, 2, 3])
check("HD.1", "kernel-derived flat trace tr# L_{p,1/2}^m = p^{+m/2} (#roots=p^m-1, Jac=1/|1-p^-m|)",
      ok_hd1, "PROVEN")
def L_fourier(p, s, n): return (p ** (1 - s), n // p) if n % p == 0 else (0.0, None)
c, mo = L_fourier(3, 0.5, 9)
check("HD.2", "L_{p,s} e_n = p^{1-s} e_{n/p} (p|n)  [de-dilation dual to rho_p]",
      abs(c - 3 ** 0.5) < 1e-9 and mo == 3, "PROVEN")
check("HD.4", "fibre exponent +1/2 != base exponent -1/2 (v1.0 conflation removed)",
      all(abs(p ** 0.5 - p ** (-0.5)) > 0.1 for p in [2, 3, 5]), "PROVEN")
def Wp(p): return np.diag([np.exp(2j * np.pi * (j - 5) / p) for j in range(Q)])
J = np.zeros((Q, Q));  [J.__setitem__((j, Q - 1 - j), 1) for j in range(Q)]
def L_op(s): return sum(p ** (-s) * Wp(p) for p in PRIMES_SMALL)
def eps_J(sig, t=0.0):
    s = sig + 1j * t
    return np.linalg.norm(J @ (L_op(s).conj().T) @ J - L_op(1 - s))
seam_ok = eps_J(0.5) < 1e-12 and min(eps_J(sg) for sg in [0.3, 0.4, 0.45, 0.55, 0.6, 0.7]) > 1e-3
check("HD.5", "seam residual eps_J(sigma)=0 iff sigma=1/2 (ZS-M7 Thm 4)", seam_ok, "DERIVED-interp")

# HD.3 is an EXTERNAL theorem (BC KMS): declared, not counted.
register("HD.3", "BC KMS_beta weight psi(mu_{p^m}mu*)=p^{-m beta}; at beta=1/2 -> p^{-m/2}",
         "IMPORTED-GUARD")

# =====================================================================
#  BLOCK ALG — internal direct-limit Bost-Connes representation  [PROVEN]
#  (closes gate H-ALG). States are dicts {k: coeff} on l^2(N^x).
# =====================================================================
banner("BLOCK ALG : internal l^2(N^x) BC representation (closes H-ALG)")
def cl(v): return {k: c for k, c in v.items() if abs(c) > 1e-12}
def mu(n, v): return cl({n * k: c for k, c in v.items()})
def mus(n, v): return cl({k // n: c for k, c in v.items() if k % n == 0})
def e_r(r, v): return cl({k: c * cmath.exp(2j * cmath.pi * (k * r.numerator) / r.denominator)
                          for k, c in v.items()})
def e_r_star(r, v): return cl({k: c * cmath.exp(-2j * cmath.pi * (k * r.numerator) / r.denominator)
                              for k, c in v.items()})
def nrm(r): return Fr(r.numerator % r.denominator, r.denominator)
from math import gcd as _gcd
def Hop(v): return cl({k: c * math.log(k) for k, c in v.items()})
def rho_e(n, r, v):
    out = {}
    for k, c in v.items():
        acc = sum(cmath.exp(2j * cmath.pi * (k * (r.numerator + j * r.denominator)) /
                            (r.denominator * n)) for j in range(n))
        out[k] = c * acc / n
    return cl(out)
def veq(v, w):
    return all(abs(v.get(k, 0) - w.get(k, 0)) < 1e-10 for k in set(v) | set(w))

TESTK = [1, 2, 3, 6, 12]
def all_k(pred): return all(pred({k: 1 + 0j}) for k in TESTK)
check("ALG.0a", "e(0) = I", all_k(lambda v: veq(e_r(Fr(0, 1), v), v)), "PROVEN")
check("ALG.0b", "e(r) e(s) = e(r+s)",
      all_k(lambda v: veq(e_r(Fr(1, 3), e_r(Fr(1, 4), v)), e_r(nrm(Fr(1, 3) + Fr(1, 4)), v))), "PROVEN")
check("ALG.0c", "e(r)^* = e(-r)",
      all_k(lambda v: veq(e_r_star(Fr(1, 3), v), e_r(nrm(Fr(-1, 3)), v))), "PROVEN")
check("ALG.1", "mu_n^* mu_n = I", all_k(lambda v: all(veq(mus(n, mu(n, v)), v) for n in [2, 3, 5])), "PROVEN")
check("ALG.2", "mu_n mu_n^* = P_{n|k} (proper isometry: != I)",
      all_k(lambda v: all(veq(mu(n, mus(n, v)), v if list(v)[0] % n == 0 else {}) for n in [2, 3])), "PROVEN")
check("ALG.3", "mu_n mu_m = mu_{nm}", all_k(lambda v: veq(mu(2, mu(3, v)), mu(6, v))), "PROVEN")
def alg3b(v):
    for (n, m) in [(2, 3), (3, 5), (4, 9), (5, 7)]:   # all coprime
        if not veq(mus(n, mu(m, v)), mu(m, mus(n, v))): return False
    return True
# non-coprime sanity on a witnessing vector (k=1): the relation must NOT hold in general
_nc_witness = not veq(mus(2, mu(4, {1: 1 + 0j})), mu(4, mus(2, {1: 1 + 0j})))
check("ALG.3b", "mu_n^* mu_m = mu_m mu_n^* for gcd(n,m)=1 (fails for non-coprime witness)",
      all_k(alg3b) and _nc_witness, "PROVEN")
check("ALG.4", "mu_n^* e(r) mu_n = e(nr)",
      all_k(lambda v: veq(mus(2, e_r(Fr(1, 3), mu(2, v))), e_r(Fr(2, 3), v))), "PROVEN")
check("ALG.5", "mu_n e(r) mu_n^* = rho_n(e(r))",
      all_k(lambda v: veq(mu(2, e_r(Fr(1, 6), mus(2, v))), rho_e(2, Fr(1, 6), v))), "PROVEN")
def comm_ok(v):
    n = 3
    lhs = {k: c for k, c in Hop(mu(n, v)).items()}
    sub = mu(n, Hop(v))
    diff = cl({k: lhs.get(k, 0) - sub.get(k, 0) for k in set(lhs) | set(sub)})
    return veq(diff, cl({k: math.log(n) * c for k, c in mu(n, v).items()}))
check("ALG.6", "[H, mu_n] = (log n) mu_n", all_k(comm_ok), "PROVEN")
def flow_ok(v):
    t, n = 0.7, 5
    em = {k: c * cmath.exp(-1j * t * math.log(k)) for k, c in v.items()}
    ep = {k: c * cmath.exp(1j * t * math.log(k)) for k, c in mu(n, em).items()}
    return veq(cl(ep), cl({k: (n ** (1j * t)) * c for k, c in mu(n, v).items()}))
check("ALG.7", "e^{itH} mu_n e^{-itH} = n^{it} mu_n", all_k(flow_ok), "PROVEN")

# =====================================================================
#  BLOCK NG — finite-dimensional isometry NO-GO (Theorem M50.NG)
# =====================================================================
banner("BLOCK NG : no proper isometry in finite dim -> infinite completion forced")
rng = np.random.default_rng(0)
ng1 = True
for d in [3, 5, 10]:
    Vq, _ = np.linalg.qr(rng.standard_normal((d, d)) + 1j * rng.standard_normal((d, d)))
    if not (np.allclose(Vq.conj().T @ Vq, np.eye(d)) and np.allclose(Vq @ Vq.conj().T, np.eye(d))):
        ng1 = False
check("NG.1", "square isometry V*V=I => V unitary => VV*=I (no proper isometry in finite dim)",
      ng1, "PROVEN")
# witness in the infinite rep: mu_2 mu_2^* kills e_1 -> range not full -> proper isometry
check("NG.2", "mu_2 mu_2^* e_1 = 0 (proper isometry exists only in infinite l^2(N^x))",
      veq(mu(2, mus(2, {1: 1 + 0j})), {}), "PROVEN")

# =====================================================================
#  BLOCK TC — Two-Clock Linearization (Theorem M50.TC)
# =====================================================================
banner("BLOCK TC : two-clock cocycle tau(k,m)=(k, log m)")
def tau(k, m): return (k, math.log(m))
def tadd(a, b): return (a[0] + b[0], a[1] + b[1])
ok_tc = True
for (k, m), (k2, m2) in [((1, 2), (2, 3)), ((0, 5), (3, 7)), ((2, 6), (1, 10))]:
    l = tau(k + k2, m * m2); r = tadd(tau(k, m), tau(k2, m2))
    if abs(l[0] - r[0]) > 0 or abs(l[1] - r[1]) > 1e-12: ok_tc = False
check("TC.1", "tau(k+k', m m') = tau(k,m) + tau(k',m') (vector-valued cocycle)", ok_tc, "PROVEN")
# vertical component rank 1 (integer clock), horizontal component infinite rank ({log p} indep)
vert_rank1 = (tau(1, 1)[0] == 1 and tau(2, 1)[0] == 2)      # first slot integer-valued
horiz_indep = mp.pslq([mp.log(2), mp.log(3), mp.log(5), mp.log(7)],
                      maxcoeff=10 ** 6, maxsteps=10 ** 4) is None
check("TC.2", "vertical clock rank-1 (Z) vs horizontal clock infinite-rank ({log p})",
      vert_rank1 and horiz_indep, "PROVEN")

# =====================================================================
#  BLOCK G — FORMAL-IDENTITY: Euler product consistency (NOT orbits)
# =====================================================================
banner("BLOCK G : weighted-measure Laplace transform (M50.3'), +1/2 shift")
print("  mu_pkt^chi = sum chi(p^m)(log p) p^{-m/2} delta_{m log p}")
print("  standard  L mu(u)     = -L'/L(u+1/2, chi)")
print("  centered  L_{1/2}mu(s)= -L'/L(s, chi)   [transform definition stated in body]")
ps = sieve(200000)
def zeta_side(s): return -mp.zeta(s, derivative=1) / mp.zeta(s)
def chi_q(a):
    a %= Q
    return 0 if a == 0 else (1 if pow(a, (Q - 1) // 2, Q) == 1 else -1)
def Lchi(s): return Q ** (-s) * sum(chi_q(aa) * mp.zeta(s, mp.mpf(aa) / Q) for aa in range(1, Q + 1))
def negLpL_chi(s): return -mp.diff(Lchi, s) / Lchi(s)

# weighted measure with EXPLICIT p^{-m/2}; standard Laplace at u : sum (log p) p^{-m/2} e^{-u m log p}
def wm_zeta(u, Mmax=60):
    tot = mp.mpf(0)
    for p in ps:
        lp = mp.log(p)
        for m in range(1, Mmax):
            term = lp * mp.mpf(p) ** (-mp.mpf(m) / 2) * mp.e ** (-u * m * lp)
            if term == 0: break
            tot += term
    return tot
def wm_chi(u, Mmax=60):
    tot = mp.mpf(0)
    for p in ps:
        cc = chi_q(p)
        if cc == 0: continue
        lp = mp.log(p)
        for m in range(1, Mmax):
            term = (cc ** m) * lp * mp.mpf(p) ** (-mp.mpf(m) / 2) * mp.e ** (-u * m * lp)
            if term == 0: break
            tot += term
    return tot

# G.1: centered transform of the weighted measure at s=3 equals -zeta'/zeta(3)
#      (L_{1/2}mu(s) = standard L mu(s-1/2); s=3 -> u=5/2, exponent m(u+1/2)=3m)
g1L = wm_zeta(mp.mpf(3) - mp.mpf("0.5")); g1R = zeta_side(mp.mpf(3))
check("G.1", f"L_1/2 mu_zeta(3) = -zeta'/zeta(3) (weighted p^-m/2; = {mp.nstr(g1R,8)})",
      abs(g1L - g1R) / abs(g1R) < 1e-8, "FORMAL-IDENTITY")
# G.2: centered transform of the weighted chi-measure at s=3 equals -L'/L(3,chi)
g2L = wm_chi(mp.mpf(3) - mp.mpf("0.5")); g2R = negLpL_chi(mp.mpf(3))
check("G.2", f"L_1/2 mu_chi(3) = -L'/L(3,chi_11) (weighted p^-m/2; = {mp.nstr(g2R,8)})",
      abs(g2L - g2R) / abs(g2R) < 1e-8, "FORMAL-IDENTITY")
# G.3: EXPLICIT +1/2 shift for the standard Laplace: L mu(u) = -L'/L(u+1/2, chi), and != -L'/L(u)
u1, u2 = mp.mpf("2.5"), mp.mpf("3.5")
shift_ok = (abs(wm_chi(u1) - negLpL_chi(u1 + mp.mpf("0.5"))) / abs(negLpL_chi(u1 + mp.mpf("0.5"))) < 1e-8
            and abs(wm_chi(u2) - negLpL_chi(u2 + mp.mpf("0.5"))) / abs(negLpL_chi(u2 + mp.mpf("0.5"))) < 1e-8)
noshift_differs = abs(wm_chi(u1) - negLpL_chi(u1)) / abs(negLpL_chi(u1)) > 1e-3
check("G.3", "standard L mu(u) = -L'/L(u+1/2, chi) (shift present; distinct from -L'/L(u))",
      shift_ok and noshift_differs, "FORMAL-IDENTITY")

# =====================================================================
#  BLOCK HBC — finite-level obstruction (single check; rest -> NG/ALG)
# =====================================================================
banner("BLOCK HBC : finite-register obstruction")
check("HBC.1", "M_p M_p^dagger = I on the Q=11 register (invertible; no proper isometry)",
      all(np.allclose(Mp(p) @ Mp(p).conj().T, np.eye(Q - 1)) for p in [2, 3, 7, 13]), "PROVEN")

# =====================================================================
#  REGISTERED GATES  (declarations; NOT counted as verification)
# =====================================================================
banner("REGISTERED GATES (declarations, not counted)")
register("T-CORE-DATA", "(Q/Z, N^x, log n, Frobenius) data match", "PROVEN")
register("T-CORE-ALG", "l^2(N^x) rep satisfies BC covariance relations (via ALG-block)", "PROVEN")
register("H-ALG", "internal BC isometries constructed (ALG.1-7) -> CLOSED", "PROVEN")
register("H-FLOW", "explicit functor BC-groupoid -> Deninger/adelic prime-orbit flow", "DERIVED-CONDITIONAL")
register("H-SB", "seam spectral line Re s=1/2 == KMS inverse temperature beta=1/2", "OPEN/HYPOTHESIS")
register("H-WEIGHT", "KMS projection expectation -> POME orbit coefficient (trace formula)", "OPEN")
register("P-TRANS", "packet transverse normalisation nu(Gamma_p)=1 (inherited from ZS-M49)", "OPEN")
register("M50.3'", "mu_pkt^chi = mu_Lambda^chi  [DERIVED-CONDITIONAL on {H-FLOW,H-SB,H-WEIGHT,P-TRANS}]",
         "DERIVED-CONDITIONAL")

# =====================================================================
#  LEDGER + FAIL-CLOSED ENFORCEMENT
# =====================================================================
banner("VERIFICATION LEDGER")
npass = sum(1 for ok, *_ in _checks if ok)
ntot = len(_checks)
from collections import Counter
for st, c in Counter(st for ok, cid, d, st in _checks).items():
    print(f"  executable [{st:<16}] : {c}")
for st, c in Counter(st for cid, d, st in _regs).items():
    print(f"  registered [{st:<16}] : {c}")
print("-" * 72)
print(f"ZS-M50 v1.3 VERIFICATION: {npass}/{ntot} executable checks PASS (fail-closed)")
print(f"                          + {len(_regs)} registered gates (not counted)")
print("(A, Q, dim Z) = (35/437, 11, 2) LOCKED  |  Zero Free Parameters")
print("H-ALG CLOSED (PROVEN); M50.3' DERIVED-CONDITIONAL on {H-FLOW,H-SB,H-WEIGHT,P-TRANS}")
print("NON-CLAIMS: not an RH/GRH proof; not an internal prime-orbit flow.")

# ---- fail-closed gates ----
if ntot != EXPECTED_CHECKS:
    print(f"\n[ABORT] executed {ntot} checks, expected {EXPECTED_CHECKS}")
    sys.exit(2)
if not all(ok for ok, *_ in _checks):
    failed = [cid for ok, cid, *_ in _checks if not ok]
    print(f"\n[ABORT] failed checks: {failed}")
    sys.exit(1)
print(f"\nAll {ntot} executable checks PASS. exit 0.")
sys.exit(0)
