"""
Z-Sim v3.1 — Cobaya MCMC Pipeline Scaffold
Target: Gate F32-12 (highest priority pending falsification gate)

This module provides:
1. Z-Spin theory class compatible with Cobaya
2. YAML template for Planck 2018 likelihood run
3. Parameter mapping (what Z-Spin predicts vs what Cobaya samples)

STATUS: SCAFFOLD — not yet executable (requires CLASS/hi_class modification)
The scaffold is the SPECIFICATION for what must be implemented.

Source: ZS-U1 §4, Paper 21 Cobaya_Template_v2_1_0.yaml
"""
import os
import json

# ═══════════════════════════════════════════════════════════
# PARAMETER CLASSIFICATION
# ═══════════════════════════════════════════════════════════

ZSPIN_PREDICTED_PARAMS = {
    # These are DERIVED from A = 35/437. Cobaya should NOT sample them.
    "H0_local_over_H0_CMB": {
        "value": 1.08339,
        "formula": "exp(A) = exp(35/437)",
        "source": "ZS-U1 §3.1",
        "status": "DERIVED",
    },
    "omega_m_eff": {
        "value": 0.29076,
        "formula": "38/121 = Omega_m_face/(1+A)",
        "source": "ZS-U1 §3.3",
        "status": "DERIVED",
    },
    "w0": {
        "value": -1.0,
        "formula": "exactly -1 at attractor",
        "source": "ZS-U1 §3.2",
        "status": "DERIVED",
    },
    "wa": {
        "value": 0.0,
        "formula": "exactly 0 at attractor",
        "source": "ZS-U1 §3.2",
        "status": "DERIVED",
    },
    "G_eff_over_G": {
        "value": 0.925847,
        "formula": "1/(1+A) = 437/472",
        "source": "ZS-F1",
        "status": "DERIVED",
    },
    "c_T_over_c": {
        "value": 1.0,
        "formula": "exactly 1 (G5=0 in Horndeski, structural)",
        "source": "ZS-A2 §2.3",
        "status": "STRUCTURAL",
    },
    "n_s_N60": {
        "value": 0.9667,
        "formula": "1 - 2/N* for N*=60",
        "source": "ZS-U1 §2",
        "status": "DERIVED",
    },
    "r_tensor": {
        "value": 0.0089,
        "formula": "16 epsilon_V from canonical slow-roll",
        "source": "ZS-U1",
        "status": "DERIVED",
    },
}

COBAYA_SAMPLED_PARAMS = {
    # These are NOT predicted by Z-Spin and must be sampled by Cobaya
    "A_s": {
        "prior": {"min": 1e-10, "max": 5e-9},
        "ref": {"dist": "norm", "loc": 2.1e-9, "scale": 3e-11},
        "latex": "A_s",
        "note": "Scalar amplitude — NOT derived from A=35/437",
    },
    "tau_reio": {
        "prior": {"min": 0.01, "max": 0.15},
        "ref": {"dist": "norm", "loc": 0.054, "scale": 0.007},
        "latex": r"\tau_{reio}",
        "note": "Reionization optical depth — NOT derived",
    },
}


def generate_cobaya_yaml(output_path: str):
    """
    Generate the Cobaya YAML template for Gate F32-12.

    Strategy (from ZS-U1 §4):
    1. Use frozen-ε approximation: m_ε ≈ 1.34 M_P → ε frozen on all cosmological scales
    2. Map Z-Spin → effective LCDM with: Ω_m → Ω_m_eff, G → G_eff, H₀ → H₀_local
    3. 2D grid scan over (A_s, τ_reio) — the only two non-predicted parameters
    4. Evaluate Planck 2018 TT+TE+EE+lowE+lensing likelihood
    """
    yaml_content = f"""# ═══════════════════════════════════════════════════════════
# Z-Spin Cosmology — Cobaya MCMC Template
# Gate F32-12: Full Planck 2018 Likelihood Test
# Generated by Z-Sim v3.1
# ═══════════════════════════════════════════════════════════
#
# STRATEGY: Frozen-ε approximation (m_ε ≈ 1.34 M_P >> H₀)
# The ε-field is kinetically frozen on all cosmological scales.
# This reduces Z-Spin to effective LCDM with rescaled parameters.
#
# Z-Spin PREDICTS (not sampled):
#   H₀_local/H₀_CMB = exp(A) = 1.08339
#   Ω_m_eff = 38/121 = 0.29076  [v6.1: face counting; was 39/121 = 0.29841]
#   w₀ = -1 (exactly), wₐ = 0 (exactly)
#   G_eff = G/(1+A) = G × 437/472
#   c_T = c (exactly, structural)
#   n_s ≈ 0.9667 (N*=60)
#   r = 0.0089
#
# Cobaya SAMPLES (not predicted):
#   A_s (scalar amplitude)
#   τ_reio (reionization optical depth)

likelihood:
  planck_2018_lowl.TT:
    # Low-ℓ TT (Commander)
  planck_2018_lowl.EE:
    # Low-ℓ EE (SimAll)
  planck_2018_highl_plik.TTTEEE:
    # High-ℓ TT+TE+EE (plik)
  planck_2018_lensing.clik:
    # CMB lensing

theory:
  classy:
    # CLASS Boltzmann solver
    # CRITICAL: Must use hi_class or modified CLASS with:
    #   - G_eff = G/(1+A) = G × 437/472
    #   - Or equivalently: rescaled M_P² → M_P²(1+A)
    extra_args:
      # Z-Spin locked parameters (NOT sampled)
      H0: 72.98                  # = 67.36 × exp(35/437)
      omega_b: 0.02237           # Planck baseline (unchanged by Z-Spin)
      omega_cdm: 0.1186          # Will be adjusted by Ω_m_eff
      # Alternative: use omega_m_eff directly
      # omega_m: 0.29076 × h² = 0.29076 × 0.7298² = 0.1549  [v6.1: was 0.29841]
      n_s: 0.9667               # Z-Spin prediction (N*=60)
      r: 0.0089                  # Z-Spin prediction
      w0_fld: -1.0               # Exact at attractor
      wa_fld: 0.0                # Exact at attractor
      # Neutrino sector (standard)
      N_ncdm: 1
      m_ncdm: 0.06
      N_ur: 2.0328

params:
  # ═══ SAMPLED (Cobaya explores these) ═══
  logA:
    prior:
      min: 1.61
      max: 3.91
    ref:
      dist: norm
      loc: 3.044
      scale: 0.014
    proposal: 0.001
    latex: \\log(10^{{10}} A_s)
    drop: true

  A_s:
    value: "lambda logA: 1e-10*np.exp(logA)"
    latex: A_s

  tau_reio:
    prior:
      min: 0.01
      max: 0.15
    ref:
      dist: norm
      loc: 0.054
      scale: 0.007
    proposal: 0.003
    latex: \\tau_{{reio}}

  # ═══ DERIVED (Z-Spin predictions, monitored but not sampled) ═══
  H0:
    value: 72.98
    latex: H_0

  sigma8:
    latex: \\sigma_8

  S8:
    derived: "lambda sigma8, omega_m: sigma8 * (omega_m / 0.3)**0.5"
    latex: S_8

sampler:
  mcmc:
    # For initial exploration, use grid scan:
    # sampler:
    #   grid:
    #     oversample: 5
    burn_in: 0.3
    max_tries: 40d
    covmat: auto
    Rminus1_stop: 0.01
    Rminus1_cl_stop: 0.2

output: zspin_planck2018
"""

    with open(output_path, 'w') as f:
        f.write(yaml_content)
    print(f"[COBAYA] Generated template: {output_path}")


def generate_grid_scan_yaml(output_path: str):
    """
    Generate a 2D grid scan YAML for quick preliminary test.
    Grid over (A_s, τ_reio) — the two non-predicted parameters.
    Source: ZS-U1 §4, Paper 32 specification.
    """
    yaml_content = """# ═══════════════════════════════════════════════════════════
# Z-Spin — Cobaya 2D Grid Scan (Preliminary)
# Gate F32-12 Step 1: Quick grid before full MCMC
# ═══════════════════════════════════════════════════════════

likelihood:
  planck_2018_lowl.TT:
  planck_2018_lowl.EE:
  planck_2018_highl_plik.TTTEEE:

theory:
  classy:
    extra_args:
      H0: 72.98
      omega_b: 0.02237
      omega_cdm: 0.1186
      n_s: 0.9667
      w0_fld: -1.0
      wa_fld: 0.0
      N_ncdm: 1
      m_ncdm: 0.06
      N_ur: 2.0328

params:
  logA:
    prior:
      min: 2.8
      max: 3.3
    ref: 3.044
  tau_reio:
    prior:
      min: 0.02
      max: 0.10
    ref: 0.054
  A_s:
    value: "lambda logA: 1e-10*np.exp(logA)"
  H0:
    value: 72.98

sampler:
  grid:
    oversample: 5

output: zspin_grid_scan
"""
    with open(output_path, 'w') as f:
        f.write(yaml_content)
    print(f"[COBAYA] Generated grid scan template: {output_path}")


def generate_cobaya_readme(output_path: str):
    """Generate README explaining the Cobaya pipeline."""
    readme = """# Z-Spin Cobaya Pipeline — Gate F32-12

## Overview
This is the scaffold for the HIGHEST PRIORITY pending falsification gate.
Until F32-12 is executed, no flagship journal submission is viable.

## What Z-Spin Predicts (NOT sampled by Cobaya)
- H₀_local/H₀_CMB = exp(A) = exp(35/437) = 1.08339
- Ω_m_eff = 38/121 = 0.29076  [v6.1: face counting; was 39/121 = 0.29841]
- w₀ = -1 (exactly at attractor), wₐ = 0
- G_eff = G/(1+A) = G × 437/472
- c_T = c (structural, G₅=0)
- n_s = 0.9667 (N*=60), r = 0.0089

## What Cobaya Samples (NOT predicted by Z-Spin)
- A_s (scalar amplitude): Planck prior ~2.1×10⁻⁹
- τ_reio (reionization optical depth): Planck prior ~0.054

## Execution Steps
1. Install Cobaya: `pip install cobaya`
2. Install CLASS: `cobaya-install cosmo -p /path/to/packages`
3. Install Planck likelihood: `cobaya-install planck_2018 -p /path/to/packages`
4. Run grid scan first: `cobaya-run zspin_grid_scan.yaml`
5. Run full MCMC: `cobaya-run zspin_planck2018.yaml`

## Critical Modification Required
Standard CLASS assumes G = G_Newton. Z-Spin requires G_eff = G/(1+A).
Two options:
  (a) Use hi_class (Horndeski CLASS) with α_M, α_T parameters
  (b) Modify CLASS source: replace G → G×437/472 in perturbation equations

## PASS/FAIL Criterion
If the best-fit χ² under Z-Spin parameters is within Δχ² < 10 of
standard LCDM best-fit, Gate F32-12 PASSES.
If Δχ² > 25 (5σ equivalent), Gate F32-12 FAILS and the framework
needs revision.

## Reference
ZS-U1 §4, Paper 32 specification
"""
    with open(output_path, 'w') as f:
        f.write(readme)
    print(f"[COBAYA] Generated README: {output_path}")


def setup_cobaya_scaffold(output_dir: str = "cobaya_scaffold"):
    """Generate all Cobaya scaffold files."""
    os.makedirs(output_dir, exist_ok=True)

    generate_cobaya_yaml(os.path.join(output_dir, "zspin_planck2018.yaml"))
    generate_grid_scan_yaml(os.path.join(output_dir, "zspin_grid_scan.yaml"))
    generate_cobaya_readme(os.path.join(output_dir, "README_F32_12.md"))

    # Save parameter classification
    params_out = {
        "predicted_by_zspin": ZSPIN_PREDICTED_PARAMS,
        "sampled_by_cobaya": COBAYA_SAMPLED_PARAMS,
    }
    with open(os.path.join(output_dir, "parameter_classification.json"), 'w') as f:
        json.dump(params_out, f, indent=2)

    print(f"\n[COBAYA] Scaffold complete: {output_dir}/")
    print(f"  - zspin_planck2018.yaml (full MCMC template)")
    print(f"  - zspin_grid_scan.yaml (quick 2D grid)")
    print(f"  - README_F32_12.md (execution instructions)")
    print(f"  - parameter_classification.json (what's predicted vs sampled)")
